version: "3.7"

services:
  postgres_prisma:
    image: postgres
    container_name: postgres_prisma
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres_prisma
